---
title: "visualizations"
output: github_document
---

```{r setup,  message = FALSE, warning = FALSE}
library(tidyverse)
library(usa)
library(mice)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%")

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

knitr::opts_chunk$set(comment = NA, message = FALSE, warning = FALSE, echo = TRUE)
```

Read in and tidy the data. 
```{r}
# Load and tidy data
ped_covid =
  read_csv("./data/p8105_final_ped_covid.csv") %>%
  mutate(
    ethnicity_race = case_when(
      race == "R3 Black or African-American"        ~ "black",
      race == "R2 Asian"                            ~ "asian",
      race == "R5 White"                            ~ "caucasian",
      race == "R1 American Indian or Alaska Native" ~ "american indian",
      race == "Multiple Selected"                   ~ "multiple",
      ethnicity == "E1 Spanish/Hispanic/Latino"     ~ "latino"
    )
  ) %>%
  mutate(
    asthma = replace_na(asthma_dx, 0),
    asthma = str_replace(asthma, ".*J.*", "1"),
    diabetes = replace_na(diabetes_dx, 0),
    diabetes = str_replace(diabetes, ".*E.*", "1"),
    zip = as.character(zip_code_set),
    service = outcomeadmission_admission_1inpatient_admit_service, 
    ed = ed_yes_no_0_365_before,
    admission_dx = admission_apr_drg,
    icu = icu_yes_no
  ) %>%
  mutate(obesity = case_when(
    bmi_value >= 30 ~ "1",
    bmi_value < 30 ~"0"
  ))
  
```

```{r}
# Merge zipcode data with latitude and longitude.
zipcode_df = 
  usa::zipcodes

ped_covid = 
  left_join(ped_covid, zipcode_df, by = "zip") %>%
  select(admitted, age, gender, ses, zip, eventdatetime, bmi_value, icu, icu_date_time, 
         systolic_bp_value, ethnicity_race, asthma, diabetes, zip, service, ed, admission_dx,
         city.y, obesity, lat, long) %>%
  mutate_at(c("admitted", "icu", "ethnicity_race", "asthma", "diabetes",
              "ed", "city.y", "obesity"), as.factor) %>%
  mutate(
    gender = factor(gender, levels = c("F", "M")),
    ethnicity_race = factor(ethnicity_race, levels = c("caucasian", "black", "latino", "asian", "american indian", "multiple", "NA"))
  ) %>%
  rename(city = city.y) 
```


```{r}
# Impute missing data
impute = mice(ped_covid, m=3, seed=111)
datacomplete = complete(impute,2)
```

```{r}
# Export csv
write_csv(datacomplete, "datacomplete.csv")
```

Some exploratory data visualizations

```{r}
#bunch of ggplots
ped_covid %>% 
  ggplot(aes(x = admitted, y = age)) +
  geom_boxplot()

ped_covid %>% 
  filter(
    gender != "NA"
  ) %>% 
  ggplot(aes(x = gender, y = age)) +
  geom_boxplot()

ped_covid %>% 
  ggplot(aes(x = admitted, y = ses)) +
  geom_boxplot()

ped_covid %>% 
  ggplot(aes(x = admitted, y = bmi_value)) +
  geom_boxplot()

ped_covid %>% 
  count(icu)

ped_covid %>% count(ethnicity_race)

ped_covid %>% 
  ggplot(aes(x = ethnicity_race)) + 
  geom_boxplot()
```

Univariate models

```{r}
#bunch of univariate logisitic regression models
glm(
  admitted ~ age,
  data = ped_covid,
  family = binomial()
  ) %>% 
  broom::tidy()
#p = 0.00337

glm(
  admitted ~ gender,
  data = ped_covid,
  family = binomial()
  ) %>% 
  broom::tidy()
#p = 0.855

glm(
  admitted ~ bmi_value,
  data = ped_covid,
  family = binomial()
  ) %>% 
  broom::tidy()
#p = 0.263

glm(
  admitted ~ obesity,
  data = ped_covid,
  family = binomial()
  ) %>% 
  broom::tidy()
#p = 0.374

glm(
  admitted ~ asthma,
  data = ped_covid,
  family = binomial()
  ) %>% 
  broom::tidy()
#p = 4.96e- 2

glm(
  admitted ~ diabetes,
  data = ped_covid,
  family = binomial()
  ) %>% 
  broom::tidy()
#p = 7.48e- 4

glm(
  admitted ~ ethnicity_race,
  data = ped_covid,
  family = binomial()
  ) %>% 
  broom::tidy()
#no significant p values
```

```{r}
#fitting multivariate logistic regression model
glm(
  admitted ~ age + gender + ethnicity_race + asthma + diabetes + obesity,
  data = ped_covid,
  family = binomial()
  ) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term, OR, starts_with("CI"), p.value) %>% 
  knitr::kable(digits = 3)
```

